import { connectDB } from './connection';
import { Product } from './models/Product';
import { Category } from './models/Category';

const PRODUCTS = [
  { id: 'vit-c-liposomal', name: 'Vitamina C Liposomal 1000mg', brand: 'Nordic Labs', category: 'Vitaminas', need: 'Energía y vitaminas', price: 28.90, priceBefore: 34.00, tag: 'Best seller', rating: 4.8, reviews: 412, short: 'Absorción superior. Refuerzo inmune diario.', benefits: ['Fortalece el sistema inmune', 'Antioxidante de alta absorción', 'Apto para uso diario'], usage: 'Tomar 1 cápsula al día con el desayuno, preferiblemente con agua.', ingredients: 'Ácido L-ascórbico, fosfolípidos de girasol, glicerina vegetal, agua purificada.', warnings: 'No exceder la dosis recomendada. Consulte a su médico durante el embarazo.', stock: 48, color: 'oklch(0.92 0.02 85)', swatchColor: 'oklch(0.75 0.14 65)', label: 'Complejo\nInmune' },
  { id: 'magnesio-glicinato', name: 'Magnesio Glicinato Puro', brand: 'Nordic Labs', category: 'Suplementos', need: 'Energía y vitaminas', price: 22.50, tag: 'Nuevo', rating: 4.9, reviews: 218, short: 'Sueño reparador y relajación muscular.', benefits: ['Mejora la calidad del sueño', 'Reduce tensión muscular', 'Apoya función nerviosa'], usage: 'Tomar 2 cápsulas 30 minutos antes de dormir.', ingredients: 'Bisglicinato de magnesio, cápsula vegetal (HPMC).', warnings: 'Mantener fuera del alcance de los niños.', stock: 30, color: 'oklch(0.9 0.03 200)', swatchColor: 'oklch(0.55 0.09 230)', label: 'Magnesio\nGlicinato' },
  { id: 'retinol-serum', name: 'Retinol Sérum 0.3%', brand: 'Clínica Dermé', category: 'Salud de la piel', need: 'Piel seca', price: 42.00, priceBefore: 52.00, tag: 'Best seller', rating: 4.7, reviews: 356, short: 'Renovación nocturna con niacinamida.', benefits: ['Reduce líneas finas', 'Suaviza textura', 'Unifica el tono'], usage: 'Aplicar 3-4 gotas por la noche sobre rostro limpio. Usar SPF de día.', ingredients: 'Retinol encapsulado, niacinamida 4%, escualano, ácido hialurónico.', warnings: 'Puede causar sensibilidad. Introducir gradualmente. Uso nocturno.', stock: 22, color: 'oklch(0.93 0.03 45)', swatchColor: 'oklch(0.65 0.15 45)', label: 'Retinol\n0.3%' },
  { id: 'baby-lotion', name: 'Loción Calmante Bebé 300ml', brand: 'Petit Soin', category: 'Cuidado del bebé', need: 'Cuidado del bebé', price: 18.00, rating: 4.9, reviews: 1204, short: 'Hipoalergénico. Con avena coloidal.', benefits: ['Hidrata pieles delicadas', 'Calma irritaciones', 'Dermatológicamente probado'], usage: 'Aplicar después del baño sobre la piel ligeramente húmeda.', ingredients: 'Agua, avena coloidal, manteca de karité, aceite de almendras dulces.', warnings: 'Solo uso tópico. Evitar contacto con los ojos.', stock: 64, color: 'oklch(0.95 0.02 85)', swatchColor: 'oklch(0.85 0.05 85)', label: 'Petit\nSoin' },
  { id: 'omega-3', name: 'Omega-3 Concentrado 2000mg', brand: 'Nordic Labs', category: 'Suplementos', need: 'Energía y vitaminas', price: 34.00, tag: 'Best seller', rating: 4.8, reviews: 890, short: 'EPA + DHA certificado IFOS.', benefits: ['Salud cardiovascular', 'Función cognitiva', 'Antiinflamatorio natural'], usage: 'Tomar 2 cápsulas al día con las comidas.', ingredients: 'Aceite de pescado purificado (EPA 800mg, DHA 400mg), vitamina E.', warnings: 'Contiene derivados de pescado.', stock: 51, color: 'oklch(0.88 0.04 75)', swatchColor: 'oklch(0.7 0.14 65)', label: 'Omega-3\nUltra' },
  { id: 'proteina-vegetal', name: 'Proteína Vegetal Chocolate 1kg', brand: 'Verde Fitness', category: 'Fitness', need: 'Fitness y recuperación', price: 48.00, priceBefore: 58.00, rating: 4.6, reviews: 312, short: '25g proteína por porción. Sin azúcar añadido.', benefits: ['Recuperación muscular', '100% plant-based', 'Sin lactosa ni gluten'], usage: 'Mezclar 1 scoop con 300ml de agua o bebida vegetal post-entreno.', ingredients: 'Proteína de guisante, arroz integral, cacao orgánico, monk fruit.', warnings: 'Elaborado en planta que procesa frutos secos.', stock: 18, color: 'oklch(0.88 0.05 45)', swatchColor: 'oklch(0.4 0.07 45)', label: 'Plant\nProtein' },
  { id: 'crema-hidratante', name: 'Crema Hidratante Ceramidas', brand: 'Clínica Dermé', category: 'Hidratantes', need: 'Piel seca', price: 26.50, rating: 4.7, reviews: 540, short: 'Barrera cutánea reforzada 24h.', benefits: ['Hidratación profunda', 'Repara la barrera', 'No comedogénico'], usage: 'Aplicar mañana y noche sobre rostro y cuello.', ingredients: 'Ceramidas NP, ácido hialurónico, pantenol, escualano.', warnings: 'Uso externo. Evitar contorno de ojos.', stock: 40, color: 'oklch(0.95 0.015 85)', swatchColor: 'oklch(0.9 0.02 85)', label: 'Ceramida\nBalm' },
  { id: 'ibuprofeno', name: 'Ibuprofeno 400mg · 20 tabletas', brand: 'Farma Estándar', category: 'Medicamentos', need: 'Energía y vitaminas', price: 6.50, rating: 4.5, reviews: 89, short: 'Analgésico y antiinflamatorio.', benefits: ['Alivia dolor leve a moderado', 'Reduce fiebre', 'Antiinflamatorio'], usage: 'Tomar 1 tableta cada 8 horas con alimentos. Máx. 3 al día.', ingredients: 'Ibuprofeno 400mg, excipientes c.s.', warnings: 'No recomendado en embarazo. Lea el prospecto.', stock: 120, color: 'oklch(0.93 0.02 200)', swatchColor: 'oklch(0.6 0.1 235)', label: 'IBP\n400mg' },
  { id: 'fragancia-verde', name: 'Eau de Parfum · Verde Jardín 50ml', brand: 'Atelier Flora', category: 'Fragancias', need: 'Piel seca', price: 78.00, tag: 'Nuevo', rating: 4.9, reviews: 76, short: 'Bergamota, higuera, almizcle blanco.', benefits: ['Duración 8h+', 'Vegano y cruelty-free', 'Fijador natural'], usage: 'Aplicar en puntos de pulso: muñecas, cuello, detrás de las orejas.', ingredients: 'Alcohol denat., aqua, parfum, limonene, linalool.', warnings: 'Inflamable. Mantener alejado del fuego.', stock: 12, color: 'oklch(0.9 0.04 140)', swatchColor: 'oklch(0.45 0.1 150)', label: 'Verde\nJardín' },
  { id: 'labial-hidratante', name: 'Labial Hidratante SPF 20', brand: 'Atelier Flora', category: 'Maquillaje', need: 'Piel seca', price: 14.00, rating: 4.8, reviews: 201, short: 'Color natural + protección solar.', benefits: ['SPF 20', 'Hidrata 8 horas', 'Sin parabenos'], usage: 'Aplicar según necesidad. Reaplicar tras comer o beber.', ingredients: 'Manteca de karité, aceite de jojoba, óxido de zinc, cera de abeja.', warnings: 'Solo uso externo.', stock: 85, color: 'oklch(0.9 0.04 25)', swatchColor: 'oklch(0.7 0.14 25)', label: 'Rose\nBalm' },
  { id: 'gel-limpiador', name: 'Gel Limpiador Suave 200ml', brand: 'Cuidado Personal', category: 'Cuidado personal', need: 'Piel seca', price: 16.50, rating: 4.6, reviews: 432, short: 'pH balanceado. Para uso diario.', benefits: ['No reseca', 'Apto para piel sensible', 'Sin sulfatos agresivos'], usage: 'Masajear sobre piel húmeda y enjuagar con agua tibia.', ingredients: 'Aqua, glicerina, coco-glucósido, pantenol, extracto de manzanilla.', warnings: 'Evitar contacto con los ojos.', stock: 72, color: 'oklch(0.92 0.02 200)', swatchColor: 'oklch(0.75 0.06 210)', label: 'Gentle\nWash' },
  { id: 'zinc-picolinato', name: 'Zinc Picolinato 30mg', brand: 'Nordic Labs', category: 'Vitaminas', need: 'Energía y vitaminas', price: 19.00, rating: 4.7, reviews: 128, short: 'Inmunidad y piel clara.', benefits: ['Soporte inmune', 'Salud de la piel', 'Alta biodisponibilidad'], usage: '1 cápsula al día con comida.', ingredients: 'Zinc picolinato, cápsula vegetal.', warnings: 'No exceder la dosis diaria recomendada.', stock: 55, color: 'oklch(0.9 0.03 75)', swatchColor: 'oklch(0.7 0.13 75)', label: 'Zinc\n30mg' },
];

const CATEGORIES = [
  { id: 'Vitaminas', label: 'Vitaminas', sub: 'Nutrición diaria', color: 'oklch(0.92 0.04 75)' },
  { id: 'Cuidado personal', label: 'Cuidado personal', sub: 'Rutina esencial', color: 'oklch(0.92 0.02 200)' },
  { id: 'Cuidado del bebé', label: 'Cuidado del bebé', sub: 'Delicado y seguro', color: 'oklch(0.95 0.02 85)' },
  { id: 'Suplementos', label: 'Suplementos', sub: 'Rendimiento total', color: 'oklch(0.9 0.04 140)' },
  { id: 'Salud de la piel', label: 'Salud de la piel', sub: 'Rutina avanzada', color: 'oklch(0.93 0.03 45)' },
  { id: 'Fitness', label: 'Fitness', sub: 'Energía y recuperación', color: 'oklch(0.9 0.05 115)' },
  { id: 'Medicamentos', label: 'Medicamentos', sub: 'Botiquín de casa', color: 'oklch(0.93 0.02 200)' },
  { id: 'Hidratantes', label: 'Hidratantes', sub: 'Barrera reforzada', color: 'oklch(0.95 0.015 85)' },
  { id: 'Fragancias', label: 'Fragancias', sub: 'Aromas limpios', color: 'oklch(0.9 0.04 140)' },
  { id: 'Maquillaje', label: 'Maquillaje', sub: 'Toque natural', color: 'oklch(0.9 0.04 25)' },
];

async function seed() {
  await connectDB();
  await Product.deleteMany({});
  await Category.deleteMany({});
  await Product.insertMany(PRODUCTS);
  await Category.insertMany(CATEGORIES);
  console.log(`Seeded ${PRODUCTS.length} products and ${CATEGORIES.length} categories`);
  process.exit(0);
}

seed().catch((e) => { console.error(e); process.exit(1); });
